config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :contacts
  resources :kinds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/kind.rb
class Kind < ApplicationRecord
  has_many :contacts
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to kind_url(@kind), notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy!

    respond_to do |format|
      format.html { redirect_to kinds_url, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/kinds/_form.html.erb
<%= form_with(model: kind, html: { class: 'form-style-6' }) do |form| %>
  <% if kind.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
        <% kind.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label (t :description), style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="dflex">
    <%= form.submit class: "btn btn-default", value: (t :description) %>
    <%= link_to (t :'go_back'), kinds_path, class: "btn btn-default"%>
  </div>
<% end %>

app/views/kinds/_kind.html.erb
<div id="<%= dom_id kind %>">
  <p>
    <strong><%= t :description %></strong>
    <%= kind.description %>
  </p>

</div>

app/views/kinds/edit.html.erb
<h1>Editing kind</h1>

<%= render "form", kind: @kind %>

<br>

<div>
  <%= link_to (t :'kinds.show'), @kind, class: "btn btn-default" %>
</div>

app/views/kinds/index.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <h1><%= @kinds.count <= 1 ? (t :'activerecord.models.kind.one') : (t :'activerecord.models.kind.other') %></h1>

  <div id="kinds">
    <% @kinds.each do |kind| %>
      <%= render kind %>
      <p>
        <%= link_to (t :'kinds.show'), kind, class: "btn btn-default" %>
      </p>
    <% end %>
  </div>

  <%= link_to (t :'kinds.new'), new_kind_path, class: "btn btn-default" %>

  <%= link_to (t :'go_back'), home_index_path, class: "btn btn-default" %>
</div>

app/views/kinds/new.html.erb
<h1>New kind</h1>

<%= render "form", kind: @kind %>

<br>

<!--<div>-->
  <%#= link_to "Back to kinds", kinds_path %>
<!--</div>-->

app/views/kinds/show.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <%= render @kind %>

  <div>
    <%= link_to (t :'kinds.edit'), edit_kind_path(@kind), class: "btn btn-default" %> |
    <%= link_to (t :'go_back'), kinds_path, class: "btn btn-default" %>

    <%= button_to (t :'kinds.destroy'), @kind, method: :delete, class: "btn btn-default" %>
  </div>
</div>