config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :contacts
  resources :kinds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @phones = Phone.page(params[:page]).per(10)
  end

  # GET /phones/1 or /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
    @contact_options = get_contacts
  end

  # GET /phones/1/edit
  def edit
    @contact_options = get_contacts

  end

  # POST /phones or /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to phone_url(@phone), notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to phone_url(@phone), notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @phone.destroy!

    respond_to do |format|
      format.html { redirect_to phones_url, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.require(:phone).permit(:phone, :contact_id)
    end

  def get_contacts
    @contacts = Contact.all
  end

end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<%= form_with(model: phone, html: { class: 'form-style-6' }) do |form| %>
  <% if phone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
        <% phone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label t :'activerecord.models.phone.one', style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label t :'activerecord.models.contact.one', style: "display: block" %>
    <%#= form.text_field :contact_id %>
    <%= collection_select(:phone, :contact_id, @contact_options, :id, :name) %>

  </div>

  <div class="dflex">
    <%= form.submit t :'phones.new', class: "btn btn-default" %>
    <%= link_to (t :'go_back'), phones_path, class: "btn btn-default"%>

  </div>
<% end %>

app/views/phones/_phone.html.erb
<div id="<%= dom_id phone %>">
  <p>
    <strong>Phone:</strong>
    <%= phone.phone %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= phone.contact_id %>
  </p>

</div>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to (t :'phones.show'), @phone, class: "btn btn-default" %>
</div>

app/views/phones/index.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <h1><%= @phones.count <= 1 ? (t :'activerecord.models.phone.one') : (t :'activerecord.models.phone.other') %></h1>


  <div id="phones">
    <% @phones.each do |phone| %>
      <%= render phone %>
      <p class="d-flex">
        <%= link_to (t :'phones.show'), phone, class: "btn btn-default" %>
        <%= button_to (t :'contacts.destroy'), @contact, method: :delete, class: "btn btn-default" %>
      </p>
    <% end %>
  </div>

  <%= link_to (t :'phones.new'), new_phone_path, class: "btn btn-default" %>

  <%= link_to (t :'go_back'), home_index_path, class: "btn btn-default" %>


  <div class="paginacao">
    <%= paginate @phones %>
  </div>
</div>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render "form", phone: @phone %>

<br>

app/views/phones/show.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <%= render @phone %>

  <div>
    <%= link_to (t :'phones.edit'), edit_phone_path(@phone), class: "btn btn-default" %> |
    <%= link_to (t :'go_back'), phones_path, class: "btn btn-default" %>

    <%= button_to (t :'phones.destroy'), @phone, method: :delete, class: "btn btn-default" %>
  </div>
</div>