config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :contacts
  resources :kinds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  has_one :address
  has_many :phones

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true, length: {minimum: 3}
  validates :email, presence: true

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :set_kinds, only: %i[ new edit update create ]

  http_basic_authenticate_with name: "jaq", password: "secret", only: :destroy

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.order(:name).page(params[:page]).per(10)
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address # informa que esse endereço será construído, como se fosse um Address.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: (t :'contacts.created') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contacts_path, notice: (t :'contacts.updated') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    # é necessario primeiro deletar o atributo que tem a propriedade "belongs_to"
    # em relacao ao contato, se nao ele fica meio que "perdido"
    # depois deleta o contato em si
    if @contact.address != nil
      @contact.address.destroy
    end
    if @contact.phones != nil
      @contact.phones.each do|phone|
        phone.destroy
      end
    end
    @contact.destroy!
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: (t :'contacts.destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.require(:contact).permit(:name, :email, :kind_id, :rmk,
                                    address_attributes: [:id, :street, :city, :state],
                                    phones_attributes: [:id, :phone, :_destroy])
  end

  def set_kinds
    @kind_options = Kind.all
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>Name:</strong>
    <%= contact.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= contact.kind_id %>
  </p>

  <p>
    <strong>Rmk:</strong>
    <%= contact.rmk %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, html: { class: 'form-style-6' }) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: lightcoral">
      <h2><%= (contact.errors.count)%> <%= t :'activerecord.errors.messages.error'%></h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%#= form.label :kind_id, style: "display: block" %>
    <%#= form.text_field :kind_id %>
    <%= form.collection_select(:kind_id, @kind_options, :id, :description) %>
  </div>

  <div> <!--field de endereco, nested_attributes-->
    <%= form.label :address, style: "display: block" %>
    <%= form.fields_for :address do |address_fields| %>
      <%= form.label :street %> <%= address_fields.text_field :street %>
      <%= form.label :city %> <%= address_fields.text_field :city %>
      <%= form.label :state %> <%= address_fields.select :state, options_for_states(@contact.address.state) %>
      <!--    Delete: <%#= address_fields.check_box :_destroy %>-->
    <% end %>
  </div>


<!--  <div id="phones">-->
    <%#= link_to_add_association 'Adicionar Telefone', form, :phones %>
    <%#= form.fields_for :phones do |phone_fields| %>
      <%#= render "phone_fields", f: phone_fields  %>
      <%##= form.label :city %> <%#= phone_fields.text_field :city %>
      <%##= form.label :state %> <%#= phone_fields.select :state, options_for_states(@contact.address.state) %>
<!--          Delete: <%##= address_fields.check_box :_destroy %>-->
    <%# end %>

<!--  </div>-->

  <div id="phones">
    <%= form.fields_for :phones do |phone_fields| %>
    <%= render "phone_fields", f:phone_fields %>
    <% end %>
  </div>

  <div class="fields">
    <%= form.label :phones, ">" %><br/>
    <%= link_to_add_association("[Adicionar Telefone]", form, :phones) %>
  </div>


  <div>
    <%= form.label :rmk, style: "display: block" %>
    <%= form.text_area :rmk %>
  </div>

  <div class="dflex">
    <%= form.submit class: "btn btn-default", value: (t :'contacts.new') %>
    <%= link_to (t :'go_back'), contacts_path, class: "btn btn-default" %>
  </div>

<% end %>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</div>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to (t :'contacts.show'), @contact %>
</div>

app/views/contacts/index.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>
  <h1><%= @contacts.count <= 1 ? (t :'activerecord.models.contact.one') : (t :'activerecord.models.contact.other') %></h1>


  <div id="contacts">
    <% @contacts.each do |contact| %>
      <div class="container" style="background: <%= cycle('white', '#F0FFF0') %>">
        <%= render contact %>
        <div class="d-flex align-items-center">
          <p>
            <%= link_to (t :'contacts.show'), contact, class: "btn btn-default" %>
            <%= link_to (t :'contacts.destroy'), contact, method: :delete, class: "btn btn-default delete",
                        data: {confirm: ("Tem certeza que deseja deletar?")}%>
          </p>
        </div>
      </div>
    <% end %>

  </div>

  <%= link_to (t :'contacts.new'), new_contact_path, class: "btn btn-default" %>

  <%= link_to (t :'go_back'), home_index_path, class: "btn btn-default" %>

  <div class="paginacao">
    <%= paginate @contacts %>

  </div>
</div>

app/views/contacts/new.html.erb
<h1>Novo contato</h1>
<%= render "form", contact: @contact %>

<br>

<!--<div>-->
  <%#= link_to "Back to contacts", contacts_path %>
<!--</div>-->

app/views/contacts/show.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <%= render @contact %>

  <div>
    <%= link_to (t :'contacts.edit'), edit_contact_path(@contact), class: "btn btn-default" %>
    <%= link_to (t :'go_back'), contacts_path, class: "btn btn-default" %>

    <%= button_to (t :'contacts.destroy'), @contact, method: :delete, class: "btn btn-default delete" %>
  </div>
</div>