config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  get 'home/index'
  root 'home#index'
  resources :phones
  resources :contacts
  resources :kinds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: %i[ show edit update destroy ]

  # GET /addresses or /addresses.json
  def index
    @addresses = Address.page(params[:page]).per(10)
  end

  # GET /addresses/1 or /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
    @contact_options = get_contacts

  end

  # GET /addresses/1/edit
  def edit
    @contact_options = get_contacts
  end

  # POST /addresses or /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to address_url(@address), notice: "Address was successfully created." }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1 or /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to address_url(@address), notice: "Address was successfully updated." }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1 or /addresses/1.json
  def destroy
    @address.destroy!

    respond_to do |format|
      format.html { redirect_to addresses_url, notice: "Address was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def address_params
      params.require(:address).permit(:street, :city, :state, :contact_id)
    end

    def get_contacts
      @contacts = Contact.all
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_address.html.erb
<div id="<%= dom_id address %>">
  <p>
    <strong>Street:</strong>
    <%= address.street %>
  </p>

  <p>
    <strong>City:</strong>
    <%= address.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= address.state %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= address.contact_id %>
  </p>

</div>

app/views/addresses/_form.html.erb
<%= form_with(model: address, html: { class: 'form-style-6' }) do |form| %>
  <% if address.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
        <% address.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :contact_id, style: "display: block" %>
    <%#= form.text_field :contact_id %>
    <%= collection_select(:address, :contact_id, @contact_options, :id, :name) %>
  </div>

  <div class="dflex">
    <%= form.submit t :'addresses.new', class: "btn btn-default"%>
    <%= link_to (t :'go_back'), addresses_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render "form", address: @address %>

<br>

<div>
  <%= link_to (t :'addresses.show'), @address, class: "btn btn-default" %>
</div>

app/views/addresses/index.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <h1><%= @addresses.count <= 1 ? (t :'activerecord.models.address.one') : (t :'activerecord.models.address.other') %></h1>


  <div id="addresses">
    <% @addresses.each do |address| %>
      <%= render address %>
      <p>
        <%= link_to (t :'addresses.show'), address, class: "btn btn-default" %>
      </p>
    <% end %>
  </div>

  <%= link_to (t :'addresses.new'), new_address_path, class: "btn btn-default" %>

  <%= link_to (t :'go_back'), home_index_path, class: "btn btn-default" %>

  <div class="paginacao">
    <%= paginate @addresses %>
  </div>
</div>

app/views/addresses/new.html.erb
<%= render "form", address: @address %>

<br>

<!--<div>-->
  <%#= link_to "Back to addresses", addresses_path %>
<!--</div>-->

app/views/addresses/show.html.erb
<div class="form-style-6">
  <p style="color: green"><%= notice %></p>

  <%= render @address %>

  <div>
    <%= link_to (t :'addresses.edit'), edit_address_path(@address), class: "btn btn-default" %> |
    <%= link_to (t :'go_back'), addresses_path, class: "btn btn-default" %>

    <%= button_to (t :'addresses.destroy'), @address, method: :delete, class: "btn btn-default" %>
  </div>
</div>